export const appTitle = "מערכת ניהול משרד רואה חשבון";

export const navItems = [
  { to: "/", label: "לוח בקרה", end: true },
  { to: "/clients", label: "לקוחות" },
  { to: "/documents", label: "מסמכים" },
  { to: "/tasks", label: "משימות" },
  { to: "/vat-calculator", label: "מחשבון מע״מ" },
  { to: "/reports", label: "דוחות חודשיים" },
  { to: "/settings", label: "הגדרות" },
];

export const pages = {
  login: {
    title: "כניסה למערכת",
    description: "הזינו את פרטי ההתחברות שלכם כדי לגשת למערכת הפנימית.",
  },
  dashboard: {
    title: "לוח בקרה",
    description: "סיכומי נתונים יוצגו לאחר חיבור למערכת.",
  },
  clients: {
    title: "לקוחות",
    description: "ניהול לקוחות המשרד, חיפוש, סינון ועריכה.",
  },
  addClient: {
    title: "הוספת לקוח",
    description: "הזינו את פרטי הלקוח החדש.",
  },
  editClient: {
    title: "עריכת לקוח",
    description: "עדכנו את פרטי הלקוח. ניתן לנקות שדות אופציונליים על ידי השארתם ריקים.",
  },
  clientDetails: {
    title: "פרטי לקוח",
    description: "צפייה בפרטי הלקוח ופעולות ניהול.",
  },
  documents: {
    title: "מסמכים",
    description: "ניהול מסמכי המשרד, העלאה, חיפוש וסינון.",
  },
  uploadDocument: {
    title: "העלאת מסמך",
    description: "העלאת מסמך חדש עם פרטים וקובץ מאושר לדוגמה.",
  },
  editDocument: {
    title: "עריכת מסמך",
    description: "עדכון פרטי המסמך. הקובץ עצמו אינו משתנה בשלב זה.",
  },
  documentDetails: {
    title: "פרטי מסמך",
    description: "צפייה בפרטי המסמך, הורדה ופעולות ניהול.",
  },
  tasks: {
    title: "משימות",
    description: "ניהול משימות המשרד, מעקב אחר עדיפויות ותאריכי יעד.",
  },
  addTask: {
    title: "הוספת משימה",
    description: "יצירת משימה חדשה עבור לקוח.",
  },
  editTask: {
    title: "עריכת משימה",
    description: "עדכון פרטי המשימה.",
  },
  vatCalculator: {
    title: "מחשבון מע״מ",
    description: "מחשבון המע״מ יתווסף בשלב מאוחר יותר.",
  },
  reports: {
    title: "דוחות חודשיים",
    description: "דוחות חודשיים יתווספו בשלב מאוחר יותר.",
  },
  settings: {
    title: "הגדרות",
    description: "הגדרות המשרד יתווספו בשלב מאוחר יותר.",
  },
  notFound: {
    title: "העמוד לא נמצא",
    description: "הכתובת שביקשת אינה קיימת במערכת.",
  },
};

export const ui = {
  emptyStateTitle: "בקרוב",
  openMenu: "פתיחת תפריט",
  closeMenu: "סגירת תפריט",
  mainNavigation: "ניווט ראשי",
  loading: "טוען...",
  error: "אירעה שגיאה",
  backToDashboard: "חזרה ללוח הבקרה",
  view: "צפייה",
  edit: "עריכה",
  notAvailable: "—",
  all: "הכל",
  resetFilters: "איפוס סינון",
  contactPhone: "טלפון",
  contactEmail: "אימייל",
  contactBusinessId: "מספר עוסק / ח.פ.",
};

export const auth = {
  emailLabel: "אימייל",
  passwordLabel: "סיסמה",
  loginButton: "כניסה",
  logoutButton: "יציאה",
  invalidLogin: "אימייל או סיסמה שגויים.",
  unexpectedError: "אירעה שגיאה בלתי צפויה. נסו שוב מאוחר יותר.",
};

export const clients = {
  fields: {
    clientName: "שם הלקוח",
    businessName: "שם העסק",
    clientType: "סוג לקוח",
    status: "סטטוס",
    phone: "טלפון",
    email: "אימייל",
    businessId: "מספר עוסק / ח.פ.",
    address: "כתובת",
    notes: "הערות פנימיות",
    notesHint: "הערות אלו מיועדות לשימוש פנימי במשרד בלבד.",
    updatedAt: "עודכן לאחרונה",
    contact: "יצירת קשר",
  },
  actions: {
    addClient: "הוספת לקוח",
    backToList: "חזרה לרשימת לקוחות",
    cancel: "ביטול",
    saveClient: "שמירת לקוח",
    saveChanges: "שמירת שינויים",
    editClient: "עריכת לקוח",
    archiveClient: "ארכוב לקוח",
    deleteClient: "מחיקה לצמיתות",
    viewDetails: "פרטי לקוח",
  },
  list: {
    searchLabel: "חיפוש לקוחות",
    searchPlaceholder: "שם, עסק, טלפון, אימייל או מספר עוסק",
    statusFilter: "סטטוס",
    typeFilter: "סוג לקוח",
    emptyTitle: "אין לקוחות עדיין",
    emptyDescription: "הוסיפו את הלקוח הראשון כדי להתחיל לנהל את פרטי המשרד.",
    noResultsTitle: "לא נמצאו לקוחות",
    noResultsDescription: "נסו לשנות את החיפוש או את מסנני הסטטוס והסוג.",
    columns: {
      name: "שם",
      business: "עסק",
      contact: "יצירת קשר",
      type: "סוג",
      status: "סטטוס",
      updated: "עודכן",
      actions: "פעולות",
    },
  },
  details: {
    sectionTitle: "פרטי לקוח",
    internalNotesLabel: "הערות פנימיות",
    noNotes: "אין הערות פנימיות.",
    notFoundTitle: "הלקוח לא נמצא",
    notFoundDescription: "ייתכן שהלקוח נמחק או שהמזהה אינו תקין.",
  },
  confirm: {
    cancel: "ביטול",
    archiveTitle: "ארכוב לקוח",
    archiveDescription:
      "הלקוח יסומן כלא פעיל ויישאר במערכת. ניתן להפעיל אותו מחדש בעריכה.",
    archiveConfirm: "ארכוב",
    deleteTitle: "מחיקה לצמיתות",
    deleteDescription:
      "פעולה זו תסיר את הלקוח לצמיתות מהמערכת. לא ניתן לשחזר את הרשומה.",
    deleteConfirm: "מחק לצמיתות",
  },
  validation: {
    clientNameRequired: "שם הלקוח הוא שדה חובה.",
    noChanges: "לא בוצעו שינויים לשמירה.",
  },
  errors: {
    loadFailed: "לא ניתן לטעון את רשימת הלקוחות.",
    loadClientFailed: "לא ניתן לטעון את פרטי הלקוח.",
    loadSummaryFailed: "לא ניתן לטעון את סיכום הלקוח.",
    saveFailed: "לא ניתן לשמור את פרטי הלקוח.",
    archiveFailed: "לא ניתן לארכב את הלקוח.",
    deleteFailed: "לא ניתן למחוק את הלקוח.",
    unexpected: "אירעה שגיאה בלתי צפויה. נסו שוב מאוחר יותר.",
  },
  workspace: {
    summary: {
      documents: "מסמכים",
      openTasks: "משימות פתוחות",
      totalBeforeVat: "סה״כ לפני מע״מ",
      vatTotal: "סה״כ מע״מ",
      totalIncludingVat: "סה״כ כולל מע״מ",
      paymentRecords: "רשומות תשלום",
      documentStatusTitle: "סטטוס מסמכים",
      statusNew: "חדש",
      statusInProgress: "בטיפול",
      statusCompleted: "הושלם",
      statusMissingInfo: "חסר מידע",
    },
    sections: {
      documents: "מסמכים",
      tasks: "משימות",
      payments: "תשלומים",
    },
    documents: {
      explanation: "עדיין אין מסמכים ללקוח זה.",
      viewAll: "כל המסמכים של הלקוח",
      addDocument: "הוספת מסמך",
      loadFailed: "לא ניתן לטעון את מסמכי הלקוח.",
    },
    tasks: {
      explanation: "עדיין אין משימות ללקוח זה.",
      viewAll: "כל המשימות של הלקוח",
      addTask: "הוספת משימה",
      loadFailed: "לא ניתן לטעון את משימות הלקוח.",
    },
    payments: {
      disabledAction: "מעקב תשלומים יתווסף בהמשך",
      explanation: "עדיין אין רשומות תשלום ללקוח זה. מעקב תשלומים יתווסף בהמשך.",
    },
    notes: {
      saveNotes: "שמירת הערות",
      saveSuccess: "הערות נשמרו בהצלחה.",
      saveFailed: "לא ניתן לשמור את ההערות.",
    },
  },
};

export const documents = {
  actions: {
    uploadDocument: "העלאת מסמך",
    addDocument: "הוספת מסמך",
    saveDocument: "שמירת מסמך",
    downloadDocument: "הורדת קובץ",
    deleteDocument: "מחיקת מסמך",
    viewDocument: "צפייה במסמך",
    backToDocuments: "חזרה לרשימת מסמכים",
    editDocument: "עריכת מסמך",
    cancel: "ביטול",
  },
  fields: {
    documentName: "שם המסמך",
    documentType: "סוג מסמך",
    documentDate: "תאריך מסמך",
    amountBeforeVat: "סכום לפני מע״מ",
    vatRate: "שיעור מע״מ (%)",
    vatAmount: "סכום מע״מ",
    totalAmount: "סה״כ כולל מע״מ",
    status: "סטטוס",
    notes: "הערות",
    client: "לקוח",
    originalFilename: "שם קובץ",
    fileSize: "גודל קובץ",
    file: "קובץ",
    fileHintTemplate: "סוגים מותרים: {extensions}. גודל מרבי: {maxSizeMb} MB.",
  },
  form: {
    infoSection: "פרטי המסמך",
    fileSection: "בחירת קובץ",
    selectClient: "בחרו לקוח",
  },
  list: {
    searchLabel: "חיפוש מסמכים",
    searchPlaceholder: "שם מסמך או הערות",
    clientFilter: "לקוח",
    typeFilter: "סוג מסמך",
    statusFilter: "סטטוס",
    monthFilter: "חודש",
    yearFilter: "שנה",
    emptyTitle: "אין מסמכים עדיין",
    emptyDescription: "העלו מסמך ראשון כדי להתחיל לנהל את תיק הלקוחות.",
    noResultsTitle: "לא נמצאו מסמכים",
    noResultsDescription: "נסו לשנות את החיפוש או את המסננים.",
    columns: {
      name: "שם",
      client: "לקוח",
      type: "סוג",
      date: "תאריך",
      total: "סה״כ",
      status: "סטטוס",
      actions: "פעולות",
    },
  },
  confirm: {
    deleteTitle: "מחיקת מסמך",
    deleteDescription:
      "פעולה זו תסיר את המסמך ואת הקובץ מהמערכת. לא ניתן לשחזר.",
    deleteConfirm: "מחק מסמך",
    cancel: "ביטול",
  },
  validation: {
    clientRequired: "יש לבחור לקוח.",
    documentNameRequired: "שם המסמך הוא שדה חובה.",
    documentDateRequired: "תאריך מסמך הוא שדה חובה.",
    amountRequired: "סכום לפני מע״מ הוא שדה חובה.",
    noChanges: "לא בוצעו שינויים לשמירה.",
  },
  errors: {
    loadFailed: "לא ניתן לטעון את רשימת המסמכים.",
    loadDocumentFailed: "לא ניתן לטעון את פרטי המסמך.",
    saveFailed: "לא ניתן לשמור את המסמך.",
    uploadFailed: "לא ניתן להעלות את המסמך.",
    downloadFailed: "לא ניתן להוריד את הקובץ.",
    deleteFailed: "לא ניתן למחוק את המסמך.",
    fileRequired: "יש לבחור קובץ להעלאה.",
    unexpected: "אירעה שגיאה בלתי צפויה. נסו שוב מאוחר יותר.",
  },
  details: {
    notFoundTitle: "המסמך לא נמצא",
    notFoundDescription: "ייתכן שהמסמך נמחק או שהמזהה אינו תקין.",
  },
};

export const tasks = {
  actions: {
    addTask: "הוספת משימה",
    saveTask: "שמירת משימה",
    saveChanges: "שמירת שינויים",
    deleteTask: "מחיקת משימה",
    markDone: "סימון כהושלם",
    editTask: "עריכת משימה",
    backToTasks: "חזרה לרשימת משימות",
  },
  fields: {
    client: "לקוח",
    document: "מסמך קשור",
    noDocument: "ללא מסמך",
    documentLoading: "טוען מסמכים…",
    title: "כותרת",
    description: "תיאור",
    dueDate: "תאריך יעד",
    priority: "עדיפות",
    status: "סטטוס",
    clientFilter: "סינון לפי לקוח",
    statusFilter: "סינון לפי סטטוס",
    priorityFilter: "סינון לפי עדיפות",
  },
  list: {
    emptyTitle: "אין משימות עדיין",
    emptyDescription: "הוסיפו משימה ראשונה כדי להתחיל לעקוב אחר עבודה פנימית.",
    noResultsTitle: "לא נמצאו משימות",
    noResultsDescription: "נסו לשנות את הסינון או להוסיף משימה חדשה.",
    columnTitle: "כותרת",
    columnClient: "לקוח",
    columnDueDate: "תאריך יעד",
    columnPriority: "עדיפות",
    columnStatus: "סטטוס",
    columnActions: "פעולות",
  },
  badges: {
    urgent: "דחוף",
    overdue: "באיחור",
  },
  confirm: {
    deleteTitle: "מחיקת משימה",
    deleteDescription: "האם למחוק את המשימה? פעולה זו אינה ניתנת לביטול.",
    deleteConfirm: "מחק משימה",
    markDoneTitle: "סימון משימה כהושלמה",
    markDoneDescription: "האם לסמן את המשימה כהושלמה?",
    markDoneConfirm: "סימון כהושלם",
    cancel: "ביטול",
  },
  validation: {
    clientRequired: "יש לבחור לקוח.",
    titleRequired: "כותרת המשימה היא שדה חובה.",
    noChanges: "לא בוצעו שינויים לשמירה.",
  },
  errors: {
    loadFailed: "לא ניתן לטעון את רשימת המשימות.",
    loadTaskFailed: "לא ניתן לטעון את פרטי המשימה.",
    saveFailed: "לא ניתן לשמור את המשימה.",
    deleteFailed: "לא ניתן למחוק את המשימה.",
    markDoneFailed: "לא ניתן לסמן את המשימה כהושלמה.",
    unexpected: "אירעה שגיאה בלתי צפויה. נסו שוב מאוחר יותר.",
  },
  details: {
    notFoundTitle: "המשימה לא נמצאה",
    notFoundDescription: "ייתכן שהמשימה נמחקה או שהמזהה אינו תקין.",
  },
  priorities: {
    low: "נמוכה",
    medium: "בינונית",
    high: "גבוהה",
    urgent: "דחוף",
  },
  statuses: {
    open: "פתוח",
    in_progress: "בטיפול",
    done: "הושלם",
  },
};
